<?php
/**
 * Страница "Форма добавления / редактирования RSS-канала".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>RSS feed editing form/h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the RSS feeds list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Title.</b> RSS feed title;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> RSS feed description;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Channel.</b> RSS feed name in URL;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Enabled.</b> RSS feed availability.</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Caching.</b> RSS feed caching.</li>
    </ul>

    <h3>Field set "Channel options"</h3>
    <p>Basic parameters of RSS feed.<p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Language.</b> RSS feed Language;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Image.</b> URL of RSS feed image file in format: .GIF, .JPEG, .PNG;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Icon (pictogram).</b> URL of the RSS feed icon file in the following formats: .GIF, .JPEG, .PNG;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Copyright.</b> Copyright notice for channel material;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>E-mail webmaster.</b> E-mail address of the person responsible for technical issues related to the channel;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Category.</b> One or more categories to which the channel belongs;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Documentation URL.</b> A URL pointing to documentation on the format used in the RSS file;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Channel lifetime, min.</b> The number of minutes that specifies how long the feed can be cached before being refreshed from the source.;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>PICS channel rating.</b> This is an element of the RSS 2.0 specification that refers to the Platform for Internet Content Selection (PICS) and content ratings. PICS allows users to filter Internet content using ratings provided by rating services. To obtain a rating label for a feed, you must describe the content type on the service's website.;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Skip hours.</b> Hint for aggregators telling them which hours (GMT) can be skipped;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Skip days.</b> Hint for aggregators telling them which days they can skip.</li>
        <li><em><b>Registering an RSS feed in the cloud</b></em></li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Domain.</b> Domain name;</li>
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Port.</b> Server port;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Path.</b> Part of URL in cloud;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Procedure.</b> Procedure name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Protocol.</b> Protocol name.</li>
        <li><em><b>RSS feed co-author</b></em></li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Co-author's name.</b> Full name or nickname;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>URL.</b> Co-author page URL;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>E-mail.</b> Co-author's e-mail.</li>
    </ul>

    <h3>Field set "Channel material output options"</h3>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Article category.</b> Category of article pages which will be in RSS feed;</li>
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Count of records.</b> Count of records in the RSS feed. If the value is "0", the count is unlimited.</li>
    </ul>
</article>