<?php
/**
 * Страница "Форма добавления / редактирования RSS-канала".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма добавления / редактирования RSS-канала</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Добавить"</b> панели инструментов списка RSS-каналов или выбора пункта <b>"Редактировать"</b> контекстного меню выбранной записи.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Заголовок.</b> Заголовок RSS-канала;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Описание.</b> Описание RSS-канала;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Канал.</b> Имя RSS-канала в URL-адресе;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Доступен.</b> Доступность RSS-канала;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Кэширование.</b> Кэширование RSS-канала;</li>
    </ul>

    <h3>Наборй полей "Параметры канала"</h3>
    <p>Основные параметры RSS-канала.<p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Язык.</b> Язык RSS-канала;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Изображение.</b> URL-адрес файла изображения RSS-канала в формате: .GIF, .JPEG, .PNG;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Значок (пиктограмма).</b> URL-адрес файла значка (пиктограммы) RSS-канала в формате: .GIF, .JPEG, .PNG;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Авторские права.</b> Уведомление об авторских правах на материал канала;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>E-mail веб-мастера.</b> Адрес электронной почты лица, ответственного за технические проблемы, связанные с каналом;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Категория.</b> Одна или несколько категорий, к которым принадлежит канал;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>URL-адрес документации.</b> URL-адрес, указывающий на документацию по формату, используемому в файле RSS;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Время жизни канала, мин.</b> Количество минут, которое указывает, как долго канал может быть кэширован перед обновлением из источника;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>PICS-рейтинг канала.</b> Это элемент спецификации RSS 2.0, который указывает на платформу для выбора интернет-контента (PICS) и рейтинги контента. PICS позволяет пользователям фильтровать интернет-контент с помощью рейтингов, которые предоставляют рейтинговые сервисы. Чтобы получить рейтинговую метку для канала, нужно описать тип контента на сайте сервиса;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Пропускать часы.</b> Подсказка для агрегаторов, сообщающая им, какие часы (время по Гринвичу) можно пропустить;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Пропускать дни.</b> Подсказка для агрегаторов, сообщающая им, какие дни можно пропустить;</li>
        <li><em><b>Регистрация RSS-канала в облаке</b></em></li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Домен.</b> Имя домена;</li>
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Порт.</b> Порт сервера;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Путь.</b> Часть URL-адреса в облаке;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Процедура.</b> Имя процедры;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Протокол.</b> Имя протокола.</li>
        <li><em><b>Соавтор RSS-канала</b></em></li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя соавтора.</b> ФИО или ник;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>URL-адрес.</b> URL-адрес страницы соавтора;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>E-mail.</b> E-mail соавтора.</li>
    </ul>

    <h3>Наборй полей "Параметры вывода материала канала"</h3>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Категория материала.</b> Категория материала страницы которой будут в RSS-канале;</li>
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Количество записей.</b> Количество записей в RSS-канале. Если значение "0", то количество неограничено.</li>
    </ul>
</article>