<?php
/**
 * Страница "Список RSS-каналов".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of RSS feeds</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list displays all RSS feeds of the site.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Date of publication.</b> Date and time of publication of the RSS feed on the site;</li>
        <li><b>Title.</b> RSS feed title;</li>
        <li><b>Description.</b> RSS feed description;</li>
        <li><b>Channel.</b> RSS feed name in URL;</li>
        <li><b>Format.</b> Web resource format (RSS, ATOM);</li>
        <li><b>Language.</b> RSS feed language;</li>
        <li><b>Enabled.</b> RSS feed availability;</li>
        <li><b>Caching.</b> RSS feed caching.</li>
        <li><b>View.</b> Navigate to RSS feed URL.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
    <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-add.svg' ?>" /> <b>Add.</b> Shows a form to add a RSS feed;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Delete.</b> Delete the selected RSS feeds;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Delete all RSS feeds;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Shows a form for editing a RSS feed;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects RSS feeds;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refreshes the list of RSS feeds;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the Navigation Bar to display information about a RSS feed;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show / Hide.</b> Shows or hides columns;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Shows the help window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows the form for searching records in the list.</li>
    </ul>
</article>