<?php
/**
 * Страница "Список RSS-каналов".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Список RSS-каналов</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>В списке отображаются все RSS-каналы сайта.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Дата публикации.</b> Дата и время публикации RSS-канала на сайте;</li>
        <li><b>Заголовок.</b> Заголовок RSS-канала;</li>
        <li><b>Описание.</b> Описание RSS-канала;</li>
        <li><b>Канал.</b> Имя RSS-канала в URL-адресе;</li>
        <li><b>Формат.</b> Формат веб-ресурса (RSS, ATOM);</li>
        <li><b>Язык.</b> Язык RSS-канала;</li>
        <li><b>Доступен.</b> Доступность RSS-канала;</li>
        <li><b>Кэширование.</b> Кэширование RSS-канала;</li>
        <li><b>Просмотреть.</b> Переход по URL-адресу RSS-канала.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
    <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-add.svg' ?>" /> <b>Добавить.</b> Вызывает форму для добавления RSS-канала;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет выделенные RSS-каналы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Очистить.</b> Удаляет все RSS-каналы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызвает форму для редактирования RSS-канала;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение RSS-канала;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список пунктов RSS-каналов;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о RSS-канале;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает  скрытые столбцы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска записей в списке.</li>
    </ul>
</article>