<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Managing RSS Feeds</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Setting up RSS feeds using the Control panel.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">List of RSS feeds</a></li>
        <li><a href="<?= $url('form') ?>">RSS feed editing form</a></li>
    </ul>
</article>